[package]
name = "project_b"
version = "0.1.0"
edition = "2024"

[dependencies]
project_lib2 = { path = "../project_lib2" }
libc = "0.2.146"
lz4-sys = "1.8.0"
ntpd = "0.1.1"
ouroboros = "0.15.6"
rand = "0.7.3"
serde.workspace = true
